/**
 * Standalone accessories catalog for /parts, mirroring the accessories offered
 * inside each configurator's "Accessories" step (Vanguard/Nomadic).
 *
 * Prices aligned with archivos/VANGUARD TRIKE DESCRIPTION ITEMS AND PRICE.docx
 * Image paths use /images/parts/ until dedicated photos are uploaded to Supabase.
 */
export const ACCESSORIES = [
  { id: 'cruise-control', name: 'Cruise Control', price: 25, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/cruise-control.png', description: 'For long-distance flights — maintains desired RPM for stable, smooth flight. Easily connects to the motor throttle.' },
  { id: 'camel-back', name: 'Camel Back for Pilot Hydration', price: 25, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/passenger-harness.png', description: 'An essential hydration bladder setup for long-endurance flights. Tucks neatly into the instrument holder pocket located on the back of the passenger seat.' },
  { id: 'sun-roof-netting', name: 'Sun-Roof Netting', price: 43, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/sun-roof-netting.png', description: 'Protects the pilot from the sun and prevents paraglider lines from tangling with the helmet or trike equipment during sideways descent.' },
  { id: 'front-bar-protection', name: 'Padded Roll Bar Protector with Handles', price: 47, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/front-bar-protection.png', description: 'Protects the passenger and provides comfortable handles; front bars are padded for a robust look.' },
  { id: 'front-brake', name: 'Front Brake', price: 120, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/front-fork.png', description: 'Additional cable brake providing extra braking power — conventional mountain-bike derived system.' },
  { id: 'rear-mirror', name: 'Rear Mirror', price: 25, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/rear-mirror.png', description: 'Essential for viewing wing position during the first quarter of lift on takeoff.' },
  { id: 'cockpit-liner', name: 'Passenger & Pilot Cockpit Protective Liner', price: 105, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/cockpit-liner.png', description: 'Protective travel cover for the pilot and passenger cockpit. Covers essential parts for trailering without creating drag.' },
  { id: 'parachute-container', name: 'Parachute Container', price: 55, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/parachute-container.png', description: 'Exclusive container for mounting on the right or left side of the harnesses.' },
  { id: 'lateral-bag', name: 'Two Side Explorer Cases (L-R)', price: 95, compatibleWith: ['vanguard'], productoId: null, image: '/images/parts/lateral-bag-explorer.png', description: 'Pair of aerodynamic side cases with extra straps for rods, tents, fuel, etc. without using internal space.' },
  { id: 'fuel-gauge-vanguard', name: 'Analog Fuel Gauge (Vanguard)', price: 119, compatibleWith: ['vanguard'], productoId: null, image: '/images/parts/fuel-gauge-vanguard.png', description: 'Analog fuel gauge for the Vanguard L-shaped tank. Requires connection to the engine electrical system if purchased without motor.' },
  { id: 'auxiliary-lights', name: 'Auxiliary Lights Kit', price: 187.10, compatibleWith: ['vanguard'], productoId: null, image: '/images/parts/auxiliary-lights.png', description: 'Two UP67 50W waterproof LED lights, position indicator lights, luxury switch, wiring and relay — installed inside the structure.' },
  { id: 'instrument-kit-vanguard', name: 'Basic Instrument Kit (Vanguard)', price: 340, compatibleWith: ['vanguard'], productoId: null, image: '/images/parts/instrument-kit-vanguard.png', description: 'TTO digital RPM, spark plug temperature, coolant temperature gauges, and 4-port USB charger. Highly recommended with the engine electrical kit.' },
  { id: 'electrical-kit', name: 'Complete Electrical Installation Kit', price: 218.20, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/electrical-kit.png', description: 'Regulator/rectifier, relays, starter solenoid, magneto test buttons, master switch, wiring harness and connectors for the selected engine.' },
  { id: 'carabiners', name: 'Two Carabiners', price: 90, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/carabiners.png', description: 'High-capacity steel carabiners (2.4 kN each — over two tons) for maximum safety.' },
  { id: 'propeller-guard', name: 'External Propeller Guard', price: 295, compatibleWith: ['vanguard'], productoId: null, image: '/images/parts/pilot-dynamic-cage.png', description: 'Prevents wing or lines from entering the propeller. Ideal for schools and beginners learning wing control.' },
  { id: 'lateral-bag-explorer', name: 'Lateral Bag Explorer', price: 85, compatibleWith: ['nomadic'], productoId: null, image: '/images/parts/lateral-bag-explorer.png', description: 'Side-mounted storage bag built to hold additional gear during cross-country exploration flights.' },
  { id: 'bottom-explorer-bag', name: 'Bottom Explorer Bag', price: 125, compatibleWith: ['nomadic'], productoId: null, image: '/images/parts/bottom-explorer-bag.png', description: 'A premium, bottom-mounted adventure bag designed to haul extensive luggage, tools, and essentials for long expeditions.' },
  { id: 'instrument-kit-nomadic', name: 'Basic Instrument Kit (Nomadic)', price: 350, compatibleWith: ['nomadic'], productoId: null, image: '/images/parts/instrument-kit-nomadic.png', description: 'Features a built-in USB charger and 3 TTO brand digital sensors tracking Cylinder Head Temperature (CHT), RPM, and radiator water temperature.' },
  { id: 'ballistic-parachute', name: 'Ballistic Parachute', price: null, compatibleWith: ['vanguard', 'nomadic'], productoId: null, image: '/images/parts/parachute-container.png', description: 'Designed with a dedicated structural compartment to house a ballistic parachute. Its strategic placement ensures it does not alter the center of gravity or interfere with the trike framework during deployment.' },
]
