/** Engine & propeller options shared by Disruptor Paramotor and Trike configurators. */

export const DISRUPTOR_ENGINES = [
  { id: 'no-engine', name: 'No Engine', power: '', basePrice: 0, description: 'Chassis only — add an engine later.' },
  {
    id: 'vittorazi-atom-80',
    name: 'Vittorazi Atom 80',
    power: '80 HP',
    basePrice: 0,
    priceTbd: true,
    description: 'Reduced weight, uncompromising efficiency.',
    image: '/images/engines/vittorazi-300-my25.jpg',
  },
  {
    id: 'vittorazi-moster-185',
    name: 'Vittorazi Moster 185 Plus',
    power: '185 cc',
    basePrice: 0,
    priceTbd: true,
    description: 'Versatility, sportiness, and performance.',
    image: '/images/engines/vittorazi-300-my25.jpg',
  },
  {
    id: 'vittorazi-moster-185-efi',
    name: 'Vittorazi Moster 185 EFI',
    power: '',
    basePrice: 0,
    priceTbd: true,
    description: 'EFI technology with reduced fuel consumption.',
    image: '/images/engines/vittorazi-300-my25.jpg',
  },
  {
    id: 'vittorazi-moster-185-factory-r',
    name: 'Vittorazi Moster 185 Factory-R',
    power: '',
    basePrice: 0,
    priceTbd: true,
    description: 'Racing performance and exclusive design.',
    image: '/images/engines/vittorazi-300-my25.jpg',
  },
  {
    id: 'vittorazi-cosmos-300',
    name: 'Vittorazi Cosmos 300',
    power: '36 HP',
    basePrice: 0,
    priceTbd: true,
    description: 'Ideal for paratrikes and tandem flight.',
    image: '/images/engines/vittorazi-300-my25.jpg',
  },
  {
    id: 'polini-130-evo',
    name: 'Polini Thor 130 EVO',
    power: '130 cc',
    basePrice: 2580,
    description: 'Advanced dual-carb engine.',
    image: '/images/engines/polini-260.jpg',
  },
  {
    id: 'polini-202-racing',
    name: 'Polini Thor 202 Racing',
    power: '202 cc',
    basePrice: 2882,
    description: 'Built for slalom competition.',
    image: '/images/engines/polini-260.jpg',
  },
  {
    id: 'polini-303',
    name: 'Polini Thor 303 EVO',
    power: '303 cc',
    basePrice: 4994,
    description: 'Outstanding performance and reliability.',
    image: '/images/engines/polini-303.jpg',
  },
  {
    id: 'sky-150',
    name: 'SKY 150',
    power: '28 HP',
    basePrice: 0,
    priceTbd: true,
    description: 'Liquid-cooled 150 cc.',
    image: '/images/engines/polini-260.jpg',
  },
  {
    id: 'sky-zeus-300',
    name: 'SKY Engine Zeus 300',
    power: '44 HP',
    basePrice: 0,
    priceTbd: true,
    description: '300 cc boxer — up to 148 kg thrust.',
    image: '/images/engines/polini-303.jpg',
  },
]

export const DISRUPTOR_PROPELLERS = [
  { id: 'no-propeller', name: 'No Propeller', description: 'Add a propeller later.', price: 0 },
  { id: 'bipala', name: 'Two-Blade Propeller', description: 'Mid-range 25 kW H30F variant.', price: 350 },
  { id: 'tripala', name: 'Three-Blade Propeller', description: 'Mid-range 25 kW H30F variant.', price: 450 },
]
